=== predis-h2020/digitaltwin/examples/sensor_metadata_schema/sensor_metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Waste Package Monitoring Sensor Metadata",
    "description": "Metadata for a waste package monitoring sensor, including its unique identifier, position, and measurement capabilities.",
    "type": "object",
    "required": [
        "sensor_id",
        "position",
        "measuring_quantity"
    ],
    "properties": {
        "sensor_id": {
            "description": "A unique identifier for the sensor.",
            "type": "string"
        },
        "package_id": {
            "description": "A unique identifier for the Waste Package where the sensor is placed.",
            "type": "string"
        },
        "position": {
            "description": "The position of the sensor defined by location and optional orientation.",
            "type": "object",
            "required": [
                "location"
            ],
            "properties": {
                "location": {
                    "description": "The XYZ coordinates of the sensor.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "orientation": {
                    "description": "The XYZ coordinates of the orientation.",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                }
            }
        },
        "measuring_quantity": {
            "description": "The type of measurement that the sensor is capable of taking.",
            "type": "object",
            "required": [
                "type",
                "unit"
            ],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "temperature", "displacement", "radioactivity", "humidity"
                    ]
                },
                "unit": {
                    "description": "SI unit.",
                    "type": "string"
                }
            }
        },
        "independent_variable": {
            "description": "The chosen variable to make the measurements as a function of.",
            "type": "object",
            "required": [
                "type",
                "unit"
            ],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "time"
                    ]
                },
                "unit": {
                    "description": "SI unit.",
                    "type": "string"
                }
            }
        }
    }
}

=== predis-h2020/digitaltwin/tests/validate_metadata/sensor_metadata.json
[{
    "sensor_id": "sensor-001",
    "package_id": "package-001",
    "position": {
        "location": [0, 1, 0]
    },
    "measuring_quantity" :       {
        "type": "temperature",
        "unit": "K"
      },
    "independent_variable":       {
        "type": "time",
        "unit": "s"
      }
  },
  {
    "sensor_id": "sensor-002",
    "package_id": "package-001",
    "position": {
        "location": [0, 2, 0],
        "orientation": [1, 0, 0]
    },
    "measuring_quantity" :       {
        "type": "displacement",
        "unit": "m"
      },
    "independent_variable":       {
        "type": "time",
        "unit": "s"
      }
  }]
